name: workflow-servicios
on:
  push:
    branches:
      - master
jobs:
  trabajo1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: listar archivos
        uses: ls -la
        